FROM node:11.3

WORKDIR /usr/src/app
COPY package*.json ./
COPY ./src src
COPY tsconfig.json .
RUN npm install && npm run build && rm -rf node_modules && npm install --production

ENTRYPOINT ["node"]
CMD ["build/src/index.js"]
